title: "Manish Prajapati – Backend Technical Lead"
description: "Portfolio | Resume | Fintech | Spring Boot | Redis | Drools | Real-time Systems"
theme: jekyll-theme-hacker

# Optional GitHub repo footer
github:
  is_project_page: true
  repository_url: https://github.com/sparrow-trajon/manish-portfolio
